# Generated by Django 2.0.1 on 2018-02-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='Anonymous', max_length=200),
        ),
    ]
