# Generated by Django 2.0.1 on 2018-02-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20180202_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Technology', 'Techonology'), ('Business', 'Business'), ('World News', 'World News'), ('Sesign', 'Design')], default='technology', max_length=200),
        ),
    ]
