# Generated by Django 2.0.1 on 2018-02-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('technology', 'Techonology'), ('business', 'Business'), ('world_news', 'World News'), ('design', 'Design')], default='technology', max_length=200),
        ),
    ]
