# Generated by Django 2.0.1 on 2018-02-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20180201_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(choices=[('technology', 'Techonology'), ('business', 'Business'), ('world_news', 'World News'), ('design', 'Design')], default='', max_length=1000),
        ),
    ]
